# Copyright (c) 2025, HUAWEI CORPORATION.  All rights reserved.
import asyncio
import logging
import pickle
import sys
import warnings
from typing import Any, Optional

import msgpack
import numpy as np
import torch
import zmq
import zmq.asyncio

try:
    import ml_dtypes
except ModuleNotFoundError:
    ml_dtypes = None

_NP_DTYPE_MAP = {
    # --- Standard types ---
    "float32": np.dtype("float32"),
    "float64": np.dtype("float64"),
    "float16": np.dtype("float16"),
    "int32": np.dtype("int32"),
    "int64": np.dtype("int64"),
    "int16": np.dtype("int16"),
    "int8": np.dtype("int8"),
    "uint8": np.dtype("uint8"),
    "bool": np.dtype("bool"),
    # --- Aliases ---
    "single": np.dtype("float32"),
    "double": np.dtype("float64"),
    "long": np.dtype("int64"),
    "int": np.dtype("int32"),
    "half": np.dtype("float16"),
}

if ml_dtypes is not None:
    _NP_DTYPE_MAP.update(
        {
            "bfloat16": np.dtype(ml_dtypes.bfloat16),
            "bf16": np.dtype(ml_dtypes.bfloat16),
            "float8": np.dtype(ml_dtypes.float8_e4m3fn),
            "fp8": np.dtype(ml_dtypes.float8_e4m3fn),
            "float8_e4m3fn": np.dtype(ml_dtypes.float8_e4m3fn),
            "fp8_e4m3": np.dtype(ml_dtypes.float8_e4m3fn),
            "float8_e5m2": np.dtype(ml_dtypes.float8_e5m2),
            "fp8_e5m2": np.dtype(ml_dtypes.float8_e5m2),
        }
    )

_MSGPACK_PRIMITIVES = (type(None), bool, int, float, str, bytes, bytearray)
_PICKLE_KEYS_MARKER = "__pickle_kwargs__"


def get_numpy_dtype(dtype_input) -> np.dtype:
    """
    Force return of np.dtype instance.
    """
    # 1. If already a dtype object, return directly
    if isinstance(dtype_input, np.dtype):
        return dtype_input

    # 2. Lookup table or convert
    if isinstance(dtype_input, str):
        if t := _NP_DTYPE_MAP.get(dtype_input):
            return t

    # 3. Fallback attempt (e.g., passing float type, or strings not in the table)
    try:
        return np.dtype(dtype_input)
    except Exception:
        raise ValueError(f"Unsupported dtype: {dtype_input}")


def torch_to_numpy(tensor: torch.Tensor) -> np.ndarray:
    """
    Smart conversion of PyTorch Tensor to NumPy, handling bf16/fp8/quantized types and non-contiguous memory cases.
    """
    # 1. Quantized types (qint8, etc.): Must extract underlying integer representation, otherwise cannot convert
    if tensor.is_quantized:
        tensor = tensor.int_repr()

    # 2. Basic cleanup: Detach from gradient
    tensor = tensor.detach()

    # 3. Memory contiguity check: view() operations require contiguous memory. If generated by slicing, must first make contiguous.
    if not tensor.is_contiguous():
        tensor = tensor.contiguous()

    # 4. BFloat16 (2 bytes): Disguise as int16 for transfer, zero-copy restoration
    if ml_dtypes is not None and tensor.dtype == torch.bfloat16:
        return tensor.view(torch.int16).cpu().numpy().view(ml_dtypes.bfloat16)

    # 5. Float8 (1 byte): Disguise as int8 for transfer, zero-copy restoration
    # Use hasattr for compatibility with older PyTorch versions
    elif ml_dtypes is not None and hasattr(torch, "float8_e4m3fn") and tensor.dtype == torch.float8_e4m3fn:
        return tensor.view(torch.int8).cpu().numpy().view(ml_dtypes.float8_e4m3fn)

    elif ml_dtypes is not None and hasattr(torch, "float8_e5m2") and tensor.dtype == torch.float8_e5m2:
        return tensor.view(torch.int8).cpu().numpy().view(ml_dtypes.float8_e5m2)

    # 6. Regular fallback (float32, int64, complex32, etc.)
    # Note: PyTorch complex32 will be automatically converted to NumPy complex64 here
    return tensor.cpu().numpy()


def serialize_batch(
    batch_data: np.ndarray | list[np.ndarray],
    batch_lens: Optional[np.ndarray] = None,
    pad_mode: Optional[str] = None,
    save_dtype: str = None,
) -> tuple[np.ndarray, list[int], str, list[tuple[int, ...]]]:
    # Take the first element to determine type
    sample = batch_data[0]
    source_dtype = sample.dtype

    if save_dtype is not None:
        target_dtype = get_numpy_dtype(save_dtype)
    else:
        target_dtype = source_dtype

    # Determine if it's a 2D matrix
    is_2d_matrix = isinstance(batch_data, np.ndarray) and batch_data.ndim == 2

    # Input is a contiguous Numpy block converted from Tensor, operate directly on Numpy
    if is_2d_matrix:
        rows, cols = batch_data.shape
        # Generate shapes: each row's shape is (cols,)
        shapes = [(cols,) for _ in range(rows)]

        # No need to Unpad
        if batch_lens is None:
            # Try Zero-copy View
            if source_dtype == target_dtype and batch_data.flags["C_CONTIGUOUS"]:
                final_buffer = batch_data.ravel()
            else:
                final_buffer = batch_data.astype(target_dtype).ravel()

            # Length is fixed to column length
            length_list = [int(cols)] * rows
        # Need to Unpad
        else:
            batch_lens = np.asarray(batch_lens).reshape(-1)
            # Validate pad input
            if len(batch_lens) != rows:
                raise ValueError(f"Batch lens length ({len(batch_lens)}) must match number of rows ({rows})")
            # Use Broadcasting to generate boolean mask
            col_indices = np.arange(cols).reshape(1, -1)
            if pad_mode == "right_pad":
                mask = col_indices < batch_lens[:, None]
            elif pad_mode == "left_pad":
                mask = col_indices >= (cols - batch_lens[:, None])
            else:
                raise ValueError("pad_mode must be 'right_pad' or 'left_pad'")

            # Masking directly extracts valid data and flattens
            valid_data = batch_data[mask]

            if source_dtype != target_dtype:
                final_buffer = valid_data.astype(target_dtype)
            else:
                final_buffer = valid_data
            # Meta calculation
            length_list = [int(l) for l in batch_lens]
            # For unpad case, each row's shape is (length,)
            shapes = [(int(l),) for l in batch_lens]
    # Input is List[Tensor]
    else:
        # Collect original shape of each tensor
        shapes = [tuple(arr.shape) for arr in batch_data]

        if batch_lens is None:
            # For equal-length arrays without unpad or variable-length arrays, directly get required length
            effective_lens = [x.size for x in batch_data]
        else:
            # Need unpad
            effective_lens = batch_lens

        # Allocate memory once
        total_elements = sum(effective_lens)
        final_buffer = np.empty(total_elements, dtype=target_dtype)

        length_list = []
        curr_offset = 0

        for i, arr in enumerate(batch_data):
            length = int(effective_lens[i])
            length_list.append(length)
            flat_src = arr.ravel()
            src_len = flat_src.size

            # Only process when source data length differs from target length
            if batch_lens is not None and src_len != length:
                if pad_mode == "right_pad":
                    flat_src = flat_src[:length]
                elif pad_mode == "left_pad":
                    flat_src = flat_src[-length:]
                else:
                    raise ValueError(f"Length mismatch ({src_len} vs {length}) but valid pad_mode not provided.")
            # Write to Buffer
            final_buffer[curr_offset : curr_offset + length] = flat_src
            curr_offset += length

    # Special type handling: Convert to standard integer types for sending (compatible with buffer protocol)
    # Note: target_dtype.name keeps the original type for metadata; only final_buffer's memory view changes
    if target_dtype.name in ("bfloat16", "bf16"):
        final_buffer = final_buffer.view(np.int16)
    elif target_dtype.name in ("float8", "fp8", "float8_e4m3fn", "fp8_e4m3", "float8_e5m2", "fp8_e5m2"):
        final_buffer = final_buffer.view(np.int8)

    return final_buffer, length_list, target_dtype.name, shapes


def deserialize_column_from_frame(
    frame: zmq.Frame, dtype_str: str, lengths: list[int], copy: bool = False, shapes: list[tuple[int, ...]] = None
) -> list[torch.Tensor]:
    if not lengths:
        return []

    # 1. Special type handling: Read as standard integer types to avoid buffer protocol issues, then convert back to original type after torch conversion
    if dtype_str in ("bfloat16", "bf16"):
        # First read as int16 (supports buffer); zero-copy operation: int16 and bf16 are both 2 bytes
        src_view = np.frombuffer(frame, dtype=np.int16)
    elif dtype_str in ("float8", "fp8", "float8_e4m3fn", "fp8_e4m3", "float8_e5m2", "fp8_e5m2"):
        # First read as int8 (supports buffer); zero-copy operation: int8 and fp8 are both 1 byte
        src_view = np.frombuffer(frame, dtype=np.int8)
    else:
        # Read other types directly
        src_view = np.frombuffer(frame, dtype=np.dtype(dtype_str))

    if src_view.size != sum(lengths):
        raise ValueError(f"Data size mismatch. Meta sums to {sum(lengths)}, Frame has {src_view.size}")

    # 2. Choose deep copy or zero-copy mode based on copy parameter
    if copy:
        # Trigger a copy, making Tensors in list non-read-only
        slab_np = src_view.copy()
        # Copy ZMQ Buffer into PyTorch contiguous memory
        slab = torch.from_numpy(slab_np)
    else:
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=UserWarning, message=".*not writable.*")
            slab = torch.from_numpy(src_view)

    # 3. Special types: Convert back to original type using PyTorch native methods
    if dtype_str in ("bfloat16", "bf16"):
        slab = slab.to(torch.bfloat16)
    elif dtype_str in ("float8", "fp8", "float8_e4m3fn", "fp8_e4m3"):
        slab = slab.to(getattr(torch, "float8_e4m3fn", torch.float16))
    elif dtype_str in ("float8_e5m2", "fp8_e5m2"):
        slab = slab.to(getattr(torch, "float8_e5m2", torch.float16))

    # Split flat tensors
    flat_tensors = list(torch.split(slab, lengths))

    # 4. Restore original dimensions based on shapes
    if shapes is not None:
        return [flat.view(shape) for flat, shape in zip(flat_tensors, shapes, strict=False)]
    else:
        return flat_tensors


def serialize_batch_pickle(batch_data: list[Any], pickle_protocol: int = None) -> tuple[bytes, list[int], str]:
    """
    Serialize arbitrary Python objects using pickle.

    Args:
        batch_data: List of Python objects to serialize (all same type per column)
        pickle_protocol: Pickle protocol version (default: pickle.HIGHEST_PROTOCOL)

    Returns:
        Tuple[bytes, List[int], str]: (concatenated pickle blobs, byte_lengths, "pickle")
    """
    if not batch_data:
        return b"", [], "pickle"

    if pickle_protocol is None:
        pickle_protocol = pickle.HIGHEST_PROTOCOL

    pickle_blobs = []
    byte_lengths = []

    for obj in batch_data:
        blob = pickle.dumps(obj, protocol=pickle_protocol)
        pickle_blobs.append(blob)
        byte_lengths.append(len(blob))

    final_buffer = b"".join(pickle_blobs)

    return final_buffer, byte_lengths, "pickle"


def deserialize_column_pickle_from_frame(frame: zmq.Frame, byte_lengths: list[int]) -> list[Any]:
    """
    Deserialize pickled Python objects from a frame.

    Args:
        frame: zmq.Frame containing concatenated pickle blobs
        byte_lengths: Byte length of each pickle blob

    Returns:
        List[Any]: Deserialized Python objects

    Raises:
        ValueError: If frame size doesn't match expected byte_lengths sum
        pickle.UnpicklingError: If pickle deserialization fails
    """

    if not byte_lengths:
        return []

    total_bytes = sum(byte_lengths)
    if total_bytes != len(frame.bytes):
        raise ValueError(f"Pickle data size mismatch. Meta sums to {total_bytes}, Frame has {len(frame.bytes)}")

    results = []
    cursor = 0

    for byte_len in byte_lengths:
        blob = frame.bytes[cursor : cursor + byte_len]
        obj = pickle.loads(blob)
        results.append(obj)
        cursor += byte_len

    return results


def get_no_pad_length(prompts: torch.Tensor, pad_id: Optional[int] = None) -> list[torch.Tensor]:
    """
    Compute the actual (unpadded) length of each prompt in the batch.

    Args:
        prompts: Tensor of shape (batch_size, seq_len).
        pad_id: Optional padding token ID. If provided, lengths are computed
                up to the first occurrence of pad_id; otherwise full length.

    Returns:
        A list of 1D tensor containing the length (number of non-pad tokens) of the corresponding prompt.
    """
    lengths: list[torch.Tensor] = []
    batch_size, seq_len = prompts.size()

    for i in range(batch_size):
        tokens = prompts[i]
        if pad_id is not None:
            # find first pad token
            pads = torch.nonzero(tokens == pad_id, as_tuple=False)
            if pads.numel() > 0:
                length = pads[0].item()
            else:
                length = seq_len
        else:
            length = seq_len

        lengths.append(torch.tensor([length]))

    return lengths


def setup_logger(name, level=logging.INFO):
    logger = logging.getLogger(name)
    logger.setLevel(level)

    # Avoid Handler accumulation due to Ray Worker reuse
    if not logger.handlers:
        # Explicitly output to stdout, Ray Log Monitor will automatically capture this stream
        sh = logging.StreamHandler(stream=sys.stdout)
        formatter = logging.Formatter("%(asctime)s - (%(name)s) - %(levelname)s - %(message)s")
        sh.setFormatter(formatter)
        logger.addHandler(sh)
        logger.propagate = False
    return logger


def _is_msgpack_native(v: Any) -> bool:
    """Conservative check for values msgpack can serialise directly."""
    if isinstance(v, _MSGPACK_PRIMITIVES):
        return True
    if isinstance(v, (list, tuple)):
        return all(_is_msgpack_native(x) for x in v)
    if isinstance(v, dict):
        return all(isinstance(k, _MSGPACK_PRIMITIVES) and _is_msgpack_native(x) for k, x in v.items())
    return False


def decode_rpc_request(payload_bytes: bytes, extra_frames) -> dict:
    """Server-side: decode msgpack payload and splice pickle side-frames back in."""
    payload = msgpack.unpackb(payload_bytes, raw=False)
    pickle_keys = payload.pop(_PICKLE_KEYS_MARKER, None)
    if pickle_keys:
        for i, key in enumerate(pickle_keys):
            payload[key] = pickle.loads(extra_frames[i].bytes)
    return payload


def encode_rpc_reply_ok(result: Any) -> bytes:
    return msgpack.packb({"ok": True, "result": result}, use_bin_type=True)


def encode_rpc_reply_err(err: BaseException) -> bytes:
    return msgpack.packb(
        {"ok": False, "error": f"{type(err).__name__}: {err}"},
        use_bin_type=True,
    )


class ZMQClient:
    """
    Thin client for the Manager's ZMQ ROUTER. Call shape:

        await client.call("allocate_indexes", topic=..., batch_size=...)
    """

    def __init__(
        self,
        ctx: zmq.asyncio.Context,
        *,
        endpoint: Optional[str] = None,
    ):
        if endpoint is None:
            raise ValueError("ManagerRpcClient: endpoint or endpoint_resolver required")
        self._ctx = ctx
        self._endpoint = endpoint
        self._loop: Optional[asyncio.AbstractEventLoop] = None
        self._lock: Optional[asyncio.Lock] = None
        self._sock: Optional[zmq.asyncio.Socket] = None

    def _reset_sock(self) -> None:
        if self._sock is not None:
            try:
                self._sock.close(linger=0)
            except Exception:
                pass
            self._sock = None

    def _rebind_loop_if_needed(self) -> asyncio.Lock:
        """Ensure lock (and transport) belong to the currently running loop."""
        try:
            cur_loop = asyncio.get_running_loop()
        except RuntimeError:
            cur_loop = None
        if cur_loop is not self._loop or self._lock is None:
            self._reset_sock()
            self._lock = asyncio.Lock()
            self._loop = cur_loop
        return self._lock

    async def call(self, method: str, **kwargs: Any) -> Any:
        # Split off values msgpack can't represent; carry them as pickle frames.
        extras: list = []
        pickle_keys: list = []
        for key in list(kwargs.keys()):
            val = kwargs[key]
            if val is None or _is_msgpack_native(val):
                continue
            extras.append(pickle.dumps(val))
            pickle_keys.append(key)
            del kwargs[key]
        if pickle_keys:
            kwargs[_PICKLE_KEYS_MARKER] = pickle_keys

        frames = [
            method.encode("utf-8"),
            msgpack.packb(kwargs, use_bin_type=True),
            *extras,
        ]

        lock = self._rebind_loop_if_needed()
        async with lock:
            if self._sock is None:
                self._sock = self._ctx.socket(zmq.DEALER)
                self._sock.setsockopt(zmq.LINGER, 0)
                self._sock.connect(self._endpoint)
            try:
                await self._sock.send_multipart(frames)
                reply = await self._sock.recv_multipart(copy=False)
            except Exception:
                self._reset_sock()
                raise

        if not reply:
            raise RuntimeError(f"Manager RPC {method!r}: empty reply")
        resp = msgpack.unpackb(reply[0].bytes, raw=False)
        if not isinstance(resp, dict) or "ok" not in resp:
            raise RuntimeError(f"Manager RPC {method!r}: bad envelope {resp!r}")
        if not resp["ok"]:
            raise RuntimeError(f"Manager RPC {method!r}: {resp.get('error')}")
        return resp["result"]
